// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBNTmUK4q1xo_19OXhwkHpOuehRD9JpA',
    appId: '1:83700052099:web:fbfbb522379371a73babb6',
    messagingSenderId: '83700052099',
    projectId: 'leitor-mangas-flutter',
    authDomain: 'leitor-mangas-flutter.firebaseapp.com',
    databaseURL: 'https://leitor-mangas-flutter.firebaseio.com',
    storageBucket: 'leitor-mangas-flutter.appspot.com',
    measurementId: 'G-37MV6EVSW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARO6WSZO_RWFcpSLcWVWYQ5iFKZvHsOh4',
    appId: '1:83700052099:android:6e98efff7511d1c43babb6',
    messagingSenderId: '83700052099',
    projectId: 'leitor-mangas-flutter',
    databaseURL: 'https://leitor-mangas-flutter.firebaseio.com',
    storageBucket: 'leitor-mangas-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCRH0XU8TEGIbnU9cEiAhDAeWDOxQTE4',
    appId: '1:83700052099:ios:5f6f16c3e70d2ff63babb6',
    messagingSenderId: '83700052099',
    projectId: 'leitor-mangas-flutter',
    databaseURL: 'https://leitor-mangas-flutter.firebaseio.com',
    storageBucket: 'leitor-mangas-flutter.appspot.com',
    androidClientId:
        '83700052099-0gto5pc5f0k92cn3lt650qd1up2eaflf.apps.googleusercontent.com',
    iosClientId:
        '83700052099-022v9ok8n3te8ptdh8osphe5272dc5nv.apps.googleusercontent.com',
    iosBundleId: 'br.com.guilherme.leitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCRH0XU8TEGIbnU9cEiAhDAeWDOxQTE4',
    appId: '1:83700052099:ios:5f6f16c3e70d2ff63babb6',
    messagingSenderId: '83700052099',
    projectId: 'leitor-mangas-flutter',
    databaseURL: 'https://leitor-mangas-flutter.firebaseio.com',
    storageBucket: 'leitor-mangas-flutter.appspot.com',
    androidClientId:
        '83700052099-0gto5pc5f0k92cn3lt650qd1up2eaflf.apps.googleusercontent.com',
    iosClientId:
        '83700052099-022v9ok8n3te8ptdh8osphe5272dc5nv.apps.googleusercontent.com',
    iosBundleId: 'br.com.guilherme.leitor',
  );
}
