name: Analizes e Testes

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Get Dependencies
      run: flutter pub get
    - name: Analyze Project
      run: flutter analyze
    - name: Run Tests
      run: flutter test --coverage
    - name: Run CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info

    # - name: Keystore Properties
    #   run: echo $KEYSTORE_PROPERTIES | base64 --decode > android/key.properties
    #   env:
    #     KEYSTORE_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
    # - name: Release Keystore
    #   run: mkdir android/app/keystore && echo $RELEASE_KEYSTORE | base64 --decode > android/app/keystore/release.keystore.jks
    #   env:
    #     RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}

    # - name: Build APK
    #   run: flutter build apk --release --target=lib/main_prod.dart

    # - name: Upload Release to Firebase App Distribution
      # uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      # with:
        # appId: ${{secrets.FIREBASE_APP_ID}}
        # token: ${{secrets.FIREBASE_TOKEN}}
        # groups: testers
        # file: build/app/outputs/apk/release/app-release.apk

    # - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64

    # - name: Exportar Coverage
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: Coverage
    #     path: coverage/

