name: Teste e Criar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Instalar Dependencias
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get

    - name: Rodar Testes
      uses: steebchen/flutter@v1.0.0
      with:
        args: test
          
    - name: Criar App
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release

