name: Teste e Criar

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.7'
    - name: Get Dependencies
      run: flutter pub get
    - name: Analyze Project
      run: flutter analyze
    - name: Run Tests
      run: flutter test
    - name: Build APK
      run: flutter build apk --release --target=lib/main_prod.dart
    - name: Upload Release to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        # groups: testers
        file: build/app/outputs/apk/release/app-release.apk
    # - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
    # - name: Exportar Release
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: release
    #     path: build/app/outputs/apk/release/

